# Generated by Django 3.2.18 on 2023-02-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('BOUGHT', 'Купил'), ('PENDING', 'В ожидании'), ('NOT AVAILABLE', 'Нет в наличии')], default='PENDING', max_length=15),
        ),
    ]
